// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgggzqzooiuoowoggfpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZ2d6cXpvb2l1b293b2dnZnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTE5NzcsImV4cCI6MjA1ODM4Nzk3N30.iRPIeVy85Nfu0pSqMtRkZlYYR6jHx9zX-sKQGj1s75M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);